# Generated by Django 2.2 on 2019-12-30 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myprofile',
            old_name='mame',
            new_name='name',
        ),
    ]
