# Generated by Django 2.2 on 2019-12-31 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20191230_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypost',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.MyProfile'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.MyProfile'),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='liked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.MyProfile'),
        ),
    ]
