# Generated by Django 2.2 on 2019-12-31 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20191231_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followuser',
            name='followed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_by', to='social.MyProfile'),
        ),
        migrations.AlterField(
            model_name='followuser',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='social.MyProfile'),
        ),
    ]
