# Generated by Django 2.2 on 2020-01-06 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_auto_20200105_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followuser',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='social.MyProfile'),
        ),
    ]
